# name: My First GitHub Actions

# on: [push]

# jobs:
#   build:
#     runs-on: self-hosted

#     strategy:
#       matrix:
#         python-version: [3.9]

#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: ${{ matrix.python-version }}

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install pytest

#     - name: Run tests
#       run: |
#         cd src
#         python -m pytest addition.py

name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        conda install -c conda-forge --file requirements.txt  # Replace with your dependencies file
        conda install -c conda-forge pytest

    - name: Run tests
      run: |
        cd src
        pytest addition.py

